### ISSUE TITLE
"Unable to import module 'list_user'"

### ISSUE THREAD

**Issue by megawubs** [rvdh/aws_lambda_bunq2ynab#1]
When I try to execute these steps:

- At "Handler", type: list_user.lambda_handler
- Click the "Test" button
- In the 'Configure Test Event' box, choose any event name and click 'Create'
- Click 'Test' again

I get the following error:

```
{
  "errorMessage": "Unable to import module 'list_user': /var/task/_cffi_backend.so: invalid ELF header",
  "errorType": "Runtime.ImportModuleError"
}
```

Any idea how to fix this?

**Comment by rvdh** [comment]
Did you upload the zipfile from this repository or create one yourself?

**Comment by megawubs** [comment]
I uploaded the one from your repo, without any changes. I did notice that the python version has changed on aws lambda to 3.7. Has this something to do with it?

**Comment by rvdh** [comment]
I think so. Is 3.6 not available anymore? If not the zipfile must be recreated using python 3.7.

**Comment by megawubs** [comment]
No its not. I can only choose 3.7

**Comment by megawubs** [comment]
Any tips on how to create the zipfile using python 3.7?

**Comment by rvdh** [comment]
https://github.com/rvdh/aws_lambda_bunq2ynab#creating-your-own-deployment-package These instructions should still work, just replace 3.6 with 3.7 where you see it :) (When I have some extra time I'll try to update the package and instructions aswell).

**Comment by megawubs** [comment]
I got it working! Had to make some changes to the code. The notification callback is registered and works 😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rvdh** [comment]
Awesome! PRs welcome! ☺️

**Comment by megawubs** [comment]
I had to change some code in order to work for joint accounts. If we want this to be more "plug and play" the code should be updated to support both. For now I just changed one endpoint and a dict key to make it work for me. 

Also added a docker-compose.yml that builds the zip file in a aws lambda build image. When I have time I'll prepare a mr you can review 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rvdh** [comment]
See https://github.com/rvdh/aws_lambda_bunq2ynab/pull/2
