### ISSUE TITLE
key header wrong

### ISSUE THREAD

**Issue by javydekoning** [rvdh/aws_lambda_bunq2ynab#3]
If you manually generate a key you need to do it like this: `openssl genrsa -out priv.pem 2048`

Otherwise you might run into `"errorMessage": "[('PEM routines', 'get_name', 'no start line')]"`

Because the file headers are different. 

`-----BEGIN OPENSSH PRIVATE KEY-----` which should be `-----BEGIN RSA PRIVATE KEY-----`

**Comment by rvdh** [comment]
Thanks! I've verified & fixed this in the instructions.
